Display 'X11'

Display X11 {
    Driver 'X11'
    Size   '120x32'
    Font   '6x8'
    Pixel  '10+0'
    Gap    '-1x-1'
    Border 20
    Buttons 2
    Foreground  '000000cc'
    Background  '00000022'
    Basecolor   '80d000'
    Bordercolor '90e000'
}

Widget Rain {
    class 'icon'
    speed 300
    bitmap {
	row1 '...*.|.....|.....|.*...|....*|..*..|.....|*....'
	row2 '*....|...*.|.....|.....|.*...|....*|..*..|.....'
	row3 '.....|*....|...*.|.....|.....|.*...|....*|..*..'
	row4 '..*..|.....|*....|...*.|.....|.....|.*...|....*'
	row5 '....*|..*..|.....|*....|...*.|.....|.....|.*...'
	row6 '.*...|....*|..*..|.....|*....|...*.|.....|.....'
	row7 '.....|.*...|....*|..*..|.....|*....|...*.|.....'
	row8 '.....|.....|.*...|....*|..*..|.....|*....|...*.'
    }
}


Widget Squirrel {
    class 'Icon'
    speed 100
    Bitmap {
	Row1 '.....|.....|.....|.....|.....|.....'
	Row2 '.....|.....|.....|.....|.....|.....'
	Row3 '.....|.....|.....|.....|.....|.....'
	Row4 '**...|.**..|..**.|...**|....*|.....'
	Row5 '*****|*****|*****|*****|*****|*****'
	Row6 '...**|..**.|.**..|**...|*....|.....'
	Row7 '.....|.....|.....|.....|.....|.....'
	Row8 '.....|.....|.....|.....|.....|.....'
    }
}



Widget CPU {
    class  'Text'
    expression  uname('machine')
    prefix 'CPU '
    width  10
    align  'L'
    style test::onoff(7)>0?'bold':'norm'
    update tick
}

Widget freememory {
    class  'Text'
    expression file::readline('/tmp/freememory',1)
	prefix 'Free:'

    width  12
    align  'R'
    update 1000
}

Widget RAM {
    class  'Text'
    expression (meminfo('MemAvailable')) / 1024 / 1024 
    postfix ' GB'	
    width  9
    precision 0
    align  'R'
    update tick
}



Widget OS {
    class 'Text'
    expression '*** '.uname('sysname').' '.uname('release').' ***'
    width 20
    align 'M'
    style 'bold'
    speed 250	
    update tick
}

Widget BusyBar {
    class 'Bar'
    expression  proc_stat::cpu('busy',   500)
    expression2 proc_stat::cpu('system', 500)
    length 10	
    direction 'E'
    update tack
}

Widget Lightning {
    class 'icon'
    bitmap {
        row1 '...***'
        row2 '..***.'
        row3 '.***..'
        row4 '.****.'
        row5 '..**..'
        row6 '.**...'
        row7 '**....'
        row8 '*.....'
    }
}

Plugin FIFO {
    FifoBufSize 80
}

Widget fifo {
    class 'Text'
    expression fifo::read()
    width 20
    align 'L'
    speed scroller
    update 500
}


Layout Default {
    Row1 {
	Col1  'OS'
    }
    Row2 {
	Col1  'CPU'
		Col13 'BusyBar'

    }
    Row3 {
	Col1  'freememory'
    }
    Row4 {
	Col1 'fifo'
	Col11 'LoadBar'
    }
   
}

Layout 'Default'

